services:
  - type: web
    name: mlnodes-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mlnodes-db
          property: connectionString
      - key: ENVIRONMENT
        value: production

databases:
  - name: mlnodes-db
    plan: free 