services:
  - type: web
    name: mlnodes-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mlnodes-db
          property: connectionString
      - key: ENVIRONMENT
        value: production

databases:
  - name: mlnodes-db
    plan: free 